# Generated by Django 3.0.3 on 2020-02-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200206_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='vote.Vote', verbose_name='Оценки'),
        ),
    ]
