# Generated by Django 3.0.3 on 2020-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20200206_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='materials', to='vote.Vote', verbose_name='Оценки'),
        ),
    ]
